project:
  type: website
  output-dir: docs
  
website:
  title: "Ezgi Elçi, PhD"
  site-url: "https://ezgielci.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - contact.qmd
    tools:
      - icon: envelope
        href: ezgi.elci@ozyegin.edu.tr
      - icon: twitter
        href: https://x.com/ezgielci35
      - icon: github
        href: https://github.com/ezgielci/ezgielci.github.io.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Ezgi Elçi"

format:
  html:
    theme: flatly
    toc: true

editor: source

resources:
  - googlec84a8fa9eb2a51bb.html
  - robots.txt
